Merge days 22,23,24, and 26
vntechies/90DaysOfDevOps pull request #19
Opened 2022-12-27 15:41 UTC by linhanphan

Mình up bản dịch cho các ngày 22,23,24, và 26 (ngày 25 hơi dài nên sẽ làm cuối tuần). Có thể vài đoạn chưa được mượt lắm nhưng mình cũng chưa có ý nào hay hơn nên bạn có thể đọc thử và đề xuất thêm.

2023-01-01 00:31 UTC, qmau94 requested changes
@linhanphan review giúp mình nha bạn :D

2023-01-02 12:46 UTC, linhanphan commented on 2022/vi/Days/day22.md
> +Mô hình OSI (Mô hình kết nối hệ thống mở) là một khuôn khổ được sử dụng để mô tả các chức năng của một hệ thống mạng. Mô hình OSI mô tả các chức năng tính toán và tạo thành một tập hợp các quy tắc và
Mình search Google thì thấy có vẻ từ "lớp" phổ biến hơn 1 chút nên mình nghĩ tạm thời có thể dùng từ này, cũng sẽ không có nhiều khác biệt lắm giữa 2 từ nhưng giờ nếu đổi thì cần rà soát và đổi lại tất cả cũng sẽ mất thời gian hơn. Hiện tại thì mình đã thay tất cả từ tầng thành lớp trong file dịch rồi nên version hiện tại dùng "lớp" cũng được.

2023-01-02 14:20 UTC, qmau94 commented
[![LGTM](https://www.lgtm.app/p/JxHXmluxa)](https://www.lgtm.app/i/JxHXmluxa)

2023-01-02 14:20 UTC, qmau94 approved these changes
[![LGTM](https://www.lgtm.app/p/JxHXmluxa)](https://www.lgtm.app/i/JxHXmluxa)

2023-01-02 14:20 UTC, merged