added d64-66
vntechies/90DaysOfDevOps pull request #31
Opened 2023-08-08 15:28 UTC by qmauvnt

resolve #30 
resolve #32

2023-08-08 15:29 UTC, qmauvnt commented
@hungran @haicasgox 2 sếp review giúp em nhé!

2023-08-08 16:46 UTC, hungran requested changes

2023-08-08 16:46 UTC, hungran commented on 2022/vi/Days/day64.md
> +Chúng ta đã đề cập một chút về Ansible là gì trong [bài viết ngày hôm qua](day63.md) Nhưng chúng ta sẽ có một số thông tin bổ sung ở đây. Thứ nhất, Ansible là sản phẩm của RedHat. Thứ hai, agentless
```suggestion
Chúng ta đã đề cập một chút về Ansible là gì trong [bài viết ngày hôm qua](day63.md) Nhưng chúng ta sẽ có một số thông tin bổ sung ở đây. Thứ nhất, Ansible là sản phẩm của RedHat. Thứ hai, agentless, kết nối thông qua SSH và chạy các câu lệnh. Thứ ba, nó đa nền tảng (Linux & macOS, WSL2) và là mã nguồn mở (cũng có tùy chọn trả phí cho doanh nghiệp).
```

2023-08-08 16:46 UTC, hungran commented on 2022/vi/Days/day64.md
> +Để chúng ta chỉ định máy chủ của mình hoặc các node mà chúng ta muốn tự động hóa với các tác vụ này, chúng ttaôi cần xác định chúng. Chúng ta có thể xác định chúng bằng cách điều hướng đến thư mục /e
```suggestion
Để chúng ta chỉ định máy chủ của mình hoặc các node mà chúng ta muốn tự động hóa với các tác vụ này, chúng ta cần xác định chúng. Chúng ta có thể xác định chúng bằng cách điều hướng đến thư mục /etc/ansible trên hệ thống của bạn.
```

2023-08-08 16:46 UTC, hungran commented on 2022/vi/Days/day64.md
> +You saw that we were able to run `ansible Linux -m ping` against our Linux machine and get a response, basically, with Ansible we can run many ad-hoc commands. Nhưng bạn có thể chạy chương trình này
```suggestion
```

2023-08-08 17:19 UTC, qmauvnt commented
Thanks for the review @hungran. Updated as suggested. Could you please review it again?

2023-08-09 15:18 UTC, hungran approved these changes
LGTM

2023-08-10 13:44 UTC, merged