Create day70.md
vntechies/90DaysOfDevOps pull request #44
Opened 2023-08-22 10:41 UTC by HieuChayA4

Translation day70

2023-08-23 16:59 UTC, qmauvnt requested changes
Thanks, @HieuChayA4, for the very first contribution!
Well done, mate! The translation is good, considering this is your first.
I commented on the typos and made minor changes to improve the expression. 
Please review it. 

After the review, can you create another PR for the blog repository to publish it to the website? Make sure you use your best picture in the contributor's folder 😂

2023-08-23 16:59 UTC, qmauvnt commented on 2022/vi/Days/day70.md
> +Nó kết nối khoảng cách giữa phát triển và vận hành bằng cách tự động hóa quá trình xây dựng, kiểm thử và triển khai ứng dụng.
```suggestion
Nó rút ngắn khoảng cách giữa phát triển và vận hành bằng cách tự động hóa quá trình xây dựng, kiểm thử và triển khai ứng dụng.
```

2023-08-23 16:59 UTC, qmauvnt commented on 2022/vi/Days/day70.md
> +Tích hợp Liên tục (CI) là một phương pháp phát triển phần mềm hiện đại hơn, trong đó sự gia tăng về thay đổi mã nguồn được thực hiện thường xuyên và đáng tin cậy hơn. Các bước làm việc xây dựng và ki
```suggestion
Tích hợp Liên tục (CI) là một phương pháp phát triển phần mềm hiện đại, trong đó thay đổi mã nguồn được thực hiện thường xuyên và đáng tin cậy hơn. Các bước xây dựng và kiểm thử tự động được kích hoạt bởi Tích hợp Liên tục đảm bảo tính tin cậy của những thay đổi mã nguồn được gộp vào kho mã nguồn.
```

2023-08-23 16:59 UTC, qmauvnt commented on 2022/vi/Days/day70.md
> +Mã nguồn/Ứng dụng sau đó được chuyển giao nhanh chóng và một cách trôi chảy như một phần của quá trình Triển khai Liên tục.
```suggestion
Mã nguồn/Ứng dụng sau đó được triển khai một cách nhanh chóng và liền mạch như một phần của quá trình Triển khai Liên tục.
```

2023-08-23 16:59 UTC, qmauvnt commented on 2022/vi/Days/day70.md
> +* Tạo điều kiện cho một quy trình hiệu quả để đưa ứng dụng ra thị trường càng nhanh càng tốt
```suggestion
* Tạo ra một quy trình hiệu quả để đưa ứng dụng ra thị trường nhanh nhất có thể
* Triển khai các bản sửa lỗi và tính năng mới liên tục mà không cần phải chờ hàng tháng hoặc hàng năm để phát hành phiên bản mới.
```

2023-08-23 16:59 UTC, qmauvnt commented on 2022/vi/Days/day70.md
> +ở [Ngày 5](day05.md) chúng ta đã đề cập khá nhiều về lý thuyết về đằng sau DevOps và như đã được đề cập ở đây rằng CI/CD Pipelines là nền móng của môi trường DevOps hiện đại.
```suggestion
Ở [Ngày 5](day05.md) chúng ta đã đề cập khá nhiều tới lý thuyết về DevOps và như đã được đề cập trong bài viết này, CI/CD Pipelines là nền móng của môi trường DevOps hiện đại.
```

2023-08-23 16:59 UTC, qmauvnt commented on 2022/vi/Days/day70.md
> +Tôi muốn nhấn mạnh một số điểm mấu chốt ở hình ảnh trên, bây giờ chúng ta đã tiến xa hơn một chút trong hành trình học DevOps cơ bản của chúng ta.
```suggestion
Tôi muốn nhấn mạnh một số điểm mấu chốt ở hình trên, bây giờ chúng ta đã tiến xa hơn một chút trong hành trình học DevOps cơ bản.
```

2023-08-23 16:59 UTC, qmauvnt commented on 2022/vi/Days/day70.md
> +Các bước trong chu kỳ là việc các nhà phát triển viết mã nguồn sau đó được xây dựng hoặc biên dịch, sau đó được **kiểm thử** để tìm lỗi và **triển khai** vào môi trường sản phẩm nơi mà nó được sử dụn
```suggestion
Các bước trong quy trình là việc các nhà phát triển viết mã nguồn sau đó được xây dựng hoặc biên dịch, sau đó được **kiểm thử** để tìm lỗi và **triển khai** vào môi trường sản phẩm nơi mà nó được sử dụng (**Operated - Vận hành** ) bởi người dùng cuối hoặc khách hàng sau đó chúng ta **theo dõi**, thu thập phản hồi và cuối cùng **lên kế hoạch** cải tiến xung quanh phản hồi đó, sau cùng là **lặp lại** toàn bộ quy trình.
```

2023-08-23 16:59 UTC, qmauvnt commented on 2022/vi/Days/day70.md
> +### Cùng đi sâu hơn một chút vào CI/CD
```suggestion
### Tìm hiểu sâu hơn về CI/CD
```

2023-08-23 16:59 UTC, qmauvnt commented on 2022/vi/Days/day70.md
> +CI là một phương pháp phát triển yêu cầu nhà phát triển tích hợp mã nguồn vào kho mã nguồn nhiều lần trong một ngày.
```suggestion
CI là một thực hành trong quy trình phát triển yêu cầu nhà phát triển tích hợp mã nguồn vào kho mã nguồn nhiều lần trong một ngày.
```

2023-08-23 16:59 UTC, qmauvnt commented on 2022/vi/Days/day70.md
> +Chuyển sang giai đoạn tiếp theo là yếu tố triển khai liên tục (CD), mà ngày càng nhiều chúng ta thường thấy trong bất kỳ phần mềm nào có sẵn trên thị trường. Tôi sẽ cho rằng chúng ta sẽ thấy một xu h
```suggestion
Chuyển sang giai đoạn tiếp theo là yếu tố triển khai liên tục (CD), mà ngày càng nhiều chúng ta thường thấy trong bất kỳ phần mềm nào có sẵn trên thị trường. Chúng ta sẽ thấy một xu hướng, nếu chúng ta nhận phần mềm từ một nhà cung cấp như Oracle hoặc Microsoft, chúng ta sẽ sử dụng chúng từ một kho lưu trữ kiểu Docker Hub, sau đó sẽ sử dụng đường ống (pipeline) triển khai liên tục của mình để triển khai các phầm mềm đó lên môi trường của chúng ta.
```

2023-08-23 16:59 UTC, qmauvnt commented on 2022/vi/Days/day70.md
> +Bây giờ chúng ta đã có phiên bản mã nguồn đã được kiểm thử và chúng ta sẵn sàng triển khai ra ngoài như tôi nói, nhà cung cấp phần mềm sẽ trải qua giai đoạn này, nhưng tôi rất tin rằng đây là cách ch
```suggestion
Bây giờ chúng ta đã có phiên bản mã nguồn đã được kiểm thử và sẵn sàng để được triển khai, nhà cung cấp phần mềm sẽ trải qua giai đoạn này, nhưng tôi rất tin rằng đây là cách chúng ta sẽ triển khai tất cả phần mềm có sẵn mà chúng ta cần trong tương lai.
```

2023-08-23 16:59 UTC, qmauvnt commented on 2022/vi/Days/day70.md
> +Bước tiếp theo của chúng ta, ít nhất là trong Ngày 1 của phiên bản 1 của việc triển khai phần mềm, là chúng ta cần đảm bảo rằng chúng ta đang kéo mã nguồn đúng đến môi trường đúng. Điều này có thể ba
```suggestion
Trong bước tiếp theo, ít nhất là trong Ngày 1 của phiên bản 1 của việc triển khai phần mềm, chúng ta cần đảm bảo việc sử dụng đúng mã nguồn cho môi trường tương ứng. Điều này có thể bao gồm việc kéo từ kho lưu trữ phần mềm (DockerHub), nhưng có khả năng chúng ta cũng sẽ kéo (pull) cấu hình bổ sung từ một kho lưu trữ mã nguồn khác, chẳng hạn cấu hình cho ứng dụng. Trong biểu đồ dưới đây, chúng ta đang kéo phiên bản phần mềm mới nhất từ DockerHub, sau đó chúng ta triển khai nó vào môi trường của mình, có thể sẽ kèm theo việc lấy cấu hình từ một kho lưu trữ Git. Công cụ CD của chúng ta đang thực hiện việc này và đẩy mọi thứ vào môi trường của chúng ta.
```

2023-08-23 16:59 UTC, qmauvnt commented on 2022/vi/Days/day70.md
> +Tôi nghĩ chúng ta có thể đã bàn về những lợi ích này nhiều lần, nhưng đó là vì nó tự động hóa những thứ mà ban đầu phải được thực hiện thủ công. Nó tìm ra các vấn đề nhỏ trước khi chúng xâm nhập vào
```suggestion
Tôi nghĩ chúng ta có thể đã bàn về những điều này nhiều lần, đó là vì nó tự động hóa những thứ mà ban đầu phải được thực hiện thủ công. Nó tìm ra các vấn đề nhỏ trước khi chúng ảnh hưởng vào mã nguồn chính, bạn có thể tưởng tượng rằng nếu bạn sử dụng mã nguồn không tốt cho khách hàng của bạn, bạn sẽ có một khoảng thời gian khó khăn!
```

2023-08-23 16:59 UTC, qmauvnt commented on 2022/vi/Days/day70.md
> +Nó cũng giúp ngăn chặn điều gọi là "nợ kỹ thuật" (technical debt), đó là ý tưởng rằng vì kho mã nguồn chính liên tục được xây dựng theo thời gian sau đó một sửa lỗi tạm thời được thực hiện vào ngày đ
```suggestion
Nó cũng giúp ngăn chặn "nợ kỹ thuật" (technical debt), vì kho mã nguồn chính liên tục được xây dựng theo thời gian sau đó một chỉnh sửa lỗi tạm thời được thực hiện vào ngày đầu tiên sẽ trở thành một chỉnh sửa lỗi đắt đỏ hơn theo thời gian, vì bây giờ chỉnh sửa đó đã được gắn chặt chẽ và được tích hợp vào tất cả các mã nguồn và logic.
```

2023-08-23 16:59 UTC, qmauvnt commented on 2022/vi/Days/day70.md
> +Tôi nghĩ nó cũng quan trọng để lưu ý rằng không phải tất cả các công cụ đều phải thực hiện cả quá trình CI và CD. Chúng ta sẽ xem xét ArgoCD, như bạn đã đoán, nó tốt ở yếu tố CD trong việc triển khai
```suggestion
Tôi nghĩ quan trọng là chúng ta cần lưu ý rằng không phải tất cả các công cụ đều phải thực hiện cả quá trình CI và CD. Chúng ta sẽ xem xét ArgoCD, như bạn có thể đoán được, nó tốt ở với CD trong việc triển khai phần mềm của chúng ta lên một cụm Kubernetes. Nhưng một công cụ như Jenkins có thể làm việc trên nhiều nền tảng khác nhau.
```

2023-08-25 02:43 UTC, qmauvnt requested changes
is that day71.md is copied from day70.md?

2023-08-25 02:45 UTC, HieuChayA4 commented
> is that day71.md copied from day70.md?

i just created a empty day71.md file, on the way translating it :>

2023-08-25 02:48 UTC, qmauvnt approved these changes
Cool, ensure you exclude those files from the PR from now on.

![image](https://github.com/vntechies/90DaysOfDevOps/assets/10303945/075e435b-9784-4f8c-b30d-d5bbd5b2d2d6)


Well done, @HieuChayA4

2023-08-25 02:49 UTC, qmauvnt commented
resolve #36 

Please make a PR on the blog repository as well!

2023-08-25 02:49 UTC, merged