Create day71.md
vntechies/90DaysOfDevOps pull request #45
Opened 2023-08-25 12:47 UTC by HieuChayA4

Create day71.md

2023-08-26 13:36 UTC, qmauvnt requested changes
@HieuChayA4 well done em, dịch siêu nhanh :D 

anh có để lại một vài comments, e chỉnh lại rồi tạo PR bên repo blog nhé!

2023-08-26 13:36 UTC, qmauvnt commented on 2022/vi/Days/day71.md
> +Đầu tiên và không muốn làm lại những gì đã có sẵn, [Tài liệu Jenkins](https://www.jenkins.io/doc/developer/architecture/) luôn là nơi để bắt đầu, nhưng tôi sẽ ghi lại các ghi chú và kiến thức của mìn
```suggestion
Đầu tiên, để không làm lại những thứ đã có sẵn, [Tài liệu chính thức của Jenkins](https://www.jenkins.io/doc/developer/architecture/) luôn là nơi để bắt đầu, dù vậy, tôi vẫn sẽ ghi lại các ghi chú và kiến thức của mình ở đây.
```

2023-08-26 13:36 UTC, qmauvnt commented on 2022/vi/Days/day71.md
> +Có rất nhiều khía cạnh khác về kiến trúc của Jenkins nếu bạn cần, chúng có khả năng master-slave, cho phép một master phân bổ các tác vụ tới môi trường Jenkins con (slave).
```suggestion
Có rất nhiều khía cạnh khác về kiến trúc của Jenkins, ví dụ như nó có khả năng hoạt động theo kiến trúc master-slave, cho phép một master phân tán tới các slave của Jenkins.
```

2023-08-26 13:36 UTC, qmauvnt commented on 2022/vi/Days/day71.md
> +Về thông tin tham khảo, Jenkins là mã nguồn mở, sẽ có nhiều doanh nghiệp yêu cầu hỗ trợ, Cloudbees là phiên bản doanh nghiệp của Jenkins mang tới sự hỗ trợ và có thể các chức năng trả phí khác cho kh
```suggestion
Để tham khảo thêm, Jenkins là mã nguồn mở, sẽ có nhiều doanh nghiệp cần được hỗ trợ, Cloudbees là phiên bản doanh nghiệp của Jenkins cung cấp hỗ trợ và các chức năng trả phí khác cho các khách hàng doanh nghiệp.
```

2023-08-26 13:36 UTC, qmauvnt commented on 2022/vi/Days/day71.md
> +Ví dụ như một khách hàng là Bosch, bạn có thể tìm hiểu về trường hợp của Bosch ở [đây](https://assets.ctfassets.net/vtn4rfaw6n2j/case-study-boschpdf/40a0b23c61992ed3ee414ae0a55b6777/case-study-bosch.
```suggestion
Ví dụ như một trong số các khách hàng là Bosch, bạn có thể tìm hiểu về trường hợp của Bosch ở [đây](https://assets.ctfassets.net/vtn4rfaw6n2j/case-study-boschpdf/40a0b23c61992ed3ee414ae0a55b6777/case-study-bosch.pdf)
```

2023-08-29 09:58 UTC, hungran approved these changes
Lgtm

2023-08-29 13:43 UTC, qmauvnt commented
![image](https://github.com/vntechies/90DaysOfDevOps/assets/10303945/24c20ad4-c37b-432e-a2b6-861e0c1a3f41)

2023-08-29 13:43 UTC, merged